
- name: install Ansible ssh key
  authorized_key:
    user: vagrant
    key: "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"

- name: copy /etc/hosts
  copy:
    src: /etc/hosts
    dest: /etc/hosts
